const { sendMail } = require('../utils/mail');

class EmailService {
  constructor() {
    this.isConfigured = this.checkConfiguration();
  }

  checkConfiguration() {
    const adminEmail = process.env.ADMIN_EMAIL;
    const adminPass = process.env.ADMIN_EMAIL_PASS;
    return !!(adminEmail && adminPass);
  }

  async sendReportEmail(recipients, reportData, reportTitle, format = 'pdf') {
    try {
      if (!this.isConfigured) {
        throw new Error('Email service not configured. Please set ADMIN_EMAIL and ADMIN_EMAIL_PASS environment variables.');
      }

      if (!recipients || recipients.trim() === '') {
        throw new Error('No recipients specified');
      }

      // Parse recipients (comma-separated)
      const emailList = recipients.split(',').map(email => email.trim()).filter(email => email);

      if (emailList.length === 0) {
        throw new Error('No valid email addresses provided');
      }

      // Create email content
      const subject = `${reportTitle} - StockPilot Report`;
      const htmlContent = this.generateReportEmailHTML(reportTitle, reportData, format);

      // Send email to each recipient
      const results = [];
      for (const email of emailList) {
        try {
          const result = await sendMail({
            to: email,
            subject: subject,
            html: htmlContent
          });
          results.push({ email, success: true, messageId: result.messageId });
        } catch (error) {
          results.push({ email, success: false, error: error.message });
        }
      }

      const successful = results.filter(r => r.success);
      const failed = results.filter(r => !r.success);
      return {
        success: successful.length > 0,
        messageId: successful[0]?.messageId,
        recipients: emailList,
        results: results
      };

    } catch (error) {
      console.error('Failed to send email:', error);
      throw new Error(`Failed to send email: ${error.message}`);
    }
  }

  generateReportEmailHTML(reportTitle, reportData, format) {
    const currentDate = new Date().toLocaleDateString();
    const currentTime = new Date().toLocaleTimeString();

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${reportTitle}</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .header { background-color: #3b82f6; color: white; padding: 20px; text-align: center; }
          .content { padding: 20px; }
          .footer { background-color: #f8f9fa; padding: 15px; text-align: center; font-size: 12px; color: #666; }
          .report-info { background-color: #f1f5f9; padding: 15px; border-radius: 5px; margin: 15px 0; }
          .data-summary { margin: 20px 0; }
          .data-summary h3 { color: #1e40af; }
          .data-summary p { margin: 5px 0; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>StockPilot Report</h1>
          <h2>${reportTitle}</h2>
        </div>
        
        <div class="content">
          <div class="report-info">
            <h3>Report Information</h3>
            <p><strong>Generated:</strong> ${currentDate} at ${currentTime}</p>
            <p><strong>Format:</strong> ${format.toUpperCase()}</p>
            <p><strong>Total Records:</strong> ${reportData.length || 0}</p>
          </div>

          <div class="data-summary">
            <h3>Report Summary</h3>
            <p>This report contains ${reportData.length || 0} records of data.</p>
            <p>The report has been generated in ${format.toUpperCase()} format and is attached to this email.</p>
          </div>

          <div class="data-summary">
            <h3>Next Steps</h3>
            <p>• Review the attached report for detailed information</p>
            <p>• Contact the system administrator if you have any questions</p>
            <p>• Access the StockPilot system for real-time data updates</p>
          </div>
        </div>

        <div class="footer">
          <p>This email was automatically generated by StockPilot Inventory Management System</p>
          <p>Please do not reply to this email</p>
        </div>
      </body>
      </html>
    `;
  }

  async testEmailConnection() {
    try {
      if (!this.isConfigured) {
        return { success: false, error: 'Email service not configured. Please set ADMIN_EMAIL and ADMIN_EMAIL_PASS environment variables.' };
      }

      // Test by sending a simple email to admin
      const testResult = await sendMail({
        to: process.env.ADMIN_EMAIL,
        subject: 'StockPilot Email Service Test',
        html: '<p>This is a test email to verify the email service is working correctly.</p>'
      });

      return { success: true, message: 'Email service is ready', messageId: testResult.messageId };
    } catch (error) {
      return { success: false, error: error.message };
    }
  }
}

module.exports = new EmailService();
